# Kafka Event Consumer Configuration
# Copy this file to your project and modify as needed

[kafka]
# Kafka broker addresses
brokers = ["localhost:9092"]

# Multiple topics to consume from (comma-separated or array)
topics = ["user-events", "order-events", "system-logs"]

# Consumer group ID
group_id = "my-consumer-group"

# Offset reset strategy: "earliest" or "latest"
auto_offset_reset = "latest"

# Maximum message size in bytes
max_bytes = 1048576

# Commit interval for offsets
commit_interval = "1s"

# Read timeout
read_timeout = "10s"

# Maximum retries for failed operations
max_retries = 3

# Retry backoff duration
retry_backoff = "1s"

[health]
# Enable health check server
enabled = true

# Health check server port
port = 8080

[logging]
# Log level: debug, info, warn, error
level = "info"

# Log format: json, text
format = "json" 